# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Greetings.
  DOMAIN: neodock

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - echo "try 'task -l' or 'task run'"
    silent: true

  run:
    desc: build and run the debug binary
    cmds:
      - cargo run
    silent: true

  release:
    desc: build the release binary
    cmds:
      - cargo build --release
    silent: true

  resources:
    desc: build gresources
    cmds:
      - glib-compile-resources resources.gresource.xml --sourcedir ./ --target ../target/resources.gresource
    dir: resources
